import Head from 'next/head'
import { useRouter } from 'next/router';
import React, { useEffect, useState } from 'react'
import WPAPI from 'wpapi'

function Library() {    
    
    // state
    const [posts, setPosts] = useState([])

    // path props
    const router = useRouter()
    const { id } = router.query

    // init wordpress endpoint
    const wp = new WPAPI({
        endpoint: 'http://storylink.local/wp-json',
      });


    useEffect(()=>{
        getPosts()
    },[id])

    const getPosts = async () => {
        console.log({id})
        if(typeof id !== "string") return
        await wp.categories().slug( id )
        .then(res => {
            var category = res[0];
            return wp.posts().categories( category.id );
        })
        .then(categoryPosts => {
            console.log( categoryPosts );
            setPosts(categoryPosts)
        });
        
    }

  return (
    <>
        <Head>
            <title>Library</title>
            <meta name="description" content="Generated by create next app" />
            <meta name="viewport" content="width=device-width, initial-scale=1" />
            <link rel="icon" href="/favicon.ico" />
        </Head>
        <main>
            <h1>Library {id}</h1>
            <p>{posts.map((value:any)=>{
                return (
                    value.title.rendered
                )
            })}</p>
        </main>
    </>

  )
}

export default Library