import Head from 'next/head'
import { useRouter } from 'next/router';
import React, { useEffect, useState } from 'react'

function Library() {    
    
    // state
    const [posts, setPosts] = useState([])

    // path props
    const router = useRouter()
    const { id } = router.query

    useEffect(()=>{
        getPosts()
    },[id])

    const getPosts = async () => {
        if(!id) return 
        fetch(`/api/${id}/posts`)
        .then(res => res.json())
        .then(data =>{
            setPosts(data)
        })
    }

  return (
    <>
        <Head>
            <title>Library</title>
            <meta name="description" content="Generated by create next app" />
            <meta name="viewport" content="width=device-width, initial-scale=1" />
            <link rel="icon" href="/favicon.ico" />
        </Head>
        <main>
            <h1>Library {id}</h1>
            <p>{posts.map((value:any)=>{
                return (
                    value.title.rendered
                )
            })}</p>
        </main>
    </>

  )
}

export default Library