import Head from 'next/head'
import Image from 'next/image'
import { Inter } from 'next/font/google'
import styles from '@/styles/Home.module.css'
import Link from 'next/link'

const inter = Inter({ subsets: ['latin'] })

export default function Home() {
  return (
    <>
      <Head>
        <title>StoryLink</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <main className='h-screen flex justify-center items-center'>
        <div>
          <h1 className='text-6xl'>StoryLink</h1>
          <div className='p-5'></div>
          <div className='flex justify-center font-bold'>
            <Link href={`/en/library`}><div className='px-2 py-1 flex justify-center items-center rounded-sm hover:scale-105 transform transition duration-250 hover:shadow-lang-card cursor-pointer'>English</div></Link>
            <Link href={`/ta/library`}><div className='px-2 py-1 flex justify-center items-center rounded-sm hover:scale-105 transform transition duration-250 hover:shadow-lang-card cursor-pointer'>Tagalog</div></Link>
          </div>
        </div>
      </main>
    </>
  )
}
